package jo.audio.util;

public class EnumerationUtils
{
    public static final String[] ORDINAL =
    {
        "first",
        "second",
        "third",
        "fourth",
        "fifth",
        "sixth",
        "seventh",
        "eighth",
        "ninth",
        "tenth",
        "eleventh",
        "twelfth",
        "thirteenth",
        "fourteenth",
        "fifteenth",
        "sixteenth",
        "seventeenth",
        "eighteenth",
        "nineteenth",
        "twentieth",
        "twenty first",
        "twenty second",
        "twenty third",
        "twenty fourth",
        "twenty fifth",
        "twenty sixth",
        "twenty seventh",
        "twenty eighth",
        "twenty ninth",
        "thirtieth",
        "thirty first",
        "thirty second",
        "thirty third",
        "thirty fourth",
        "thirty fifth",
        "thirty sixth",
        "thirty seventh",
        "thirty eighth",
        "thirty ninth",
        "fortieth",
        "forty first",
        "forty second",
        "forty third",
        "forty fourth",
        "forty fifth",
        "forty sixth",
        "forty seventh",
        "forty eighth",
        "forty ninth",
        "fiftieth",
        "fifty first",
        "fifty second",
        "fifty third",
        "fifty fourth",
        "fifty fifth",
        "fifty sixth",
        "fifty seventh",
        "fifty eighth",
        "fifty ninth",
        "fiftieth",
        "fifty first",
        "fifty second",
        "fifty third",
        "fifty fourth",
        "fifty fifth",
        "fifty sixth",
        "fifty seventh",
        "fifty eighth",
        "fifty ninth",
        "sixtieth",
        "sixty first",
        "sixty second",
        "sixty third",
        "sixty fourth",
        "sixty fifth",
        "sixty sixth",
        "sixty seventh",
        "sixty eighth",
        "sixty ninth",
        "seventieth",
        "seventy first",
        "seventy second",
        "seventy third",
        "seventy fourth",
        "seventy fifth",
        "seventy sixth",
        "seventy seventh",
        "seventy eighth",
        "seventy ninth",
        "eightieth",
        "eighty first",
        "eighty second",
        "eighty third",
        "eighty fourth",
        "eighty fifth",
        "eighty sixth",
        "eighty seventh",
        "eighty eighth",
        "eighty ninth",
        "ninetieth",
        "ninety first",
        "ninety second",
        "ninety third",
        "ninety fourth",
        "ninety fifth",
        "ninety sixth",
        "ninety seventh",
        "ninety eighth",
        "ninety ninth",
        "one hundredth"
    };
    public static final String[] CARDINAL = 
    {
        "one",
        "two",
        "three",
        "four",
        "five",
        "six",
        "seven",
        "eight",
        "nine",
        "ten",
        "eleven",
        "twelve",
        "thirteen",
        "fourteen",
        "fifteen",
        "sixteen",
        "seventeen",
        "eighteen",
        "nineteen",
        "twenty",
        "twenty one",
        "twenty two",
        "twenty three",
        "twenty four",
        "twenty five",
        "twenty six",
        "twenty seven",
        "twenty eight",
        "twenty nine",
        "thirty",
        "thirty one",
        "thirty two",
        "thirty three",
        "thirty four",
        "thirty five",
        "thirty six",
        "thirty seven",
        "thirty eight",
        "thirty nine",
        "forty",
        "forty one",
        "forty two",
        "forty three",
        "forty four",
        "forty five",
        "forty six",
        "forty seven",
        "forty eight",
        "forty nine",
        "fifty",
        "fifty one",
        "fifty two",
        "fifty three",
        "fifty four",
        "fifty five",
        "fifty six",
        "fifty seven",
        "fifty eight",
        "fifty nine",
        "sixty",
        "sixty one",
        "sixty two",
        "sixty three",
        "sixty four",
        "sixty five",
        "sixty six",
        "sixty seven",
        "sixty eight",
        "sixty nine",
        "seventy",
        "seventy one",
        "seventy two",
        "seventy three",
        "seventy four",
        "seventy five",
        "seventy six",
        "seventy seven",
        "seventy eight",
        "seventy nine",
        "eighty",
        "eighty one",
        "eighty two",
        "eighty three",
        "eighty four",
        "eighty five",
        "eighty six",
        "eighty seven",
        "eighty eight",
        "eighty nine",
        "ninety",
        "ninety one",
        "ninety two",
        "ninety three",
        "ninety four",
        "ninety five",
        "ninety six",
        "ninety seven",
        "ninety eight",
        "ninety nine",
        "one hundred",
        "one hundred and one",
        "one hundred and two",
        "one hundred and three",
        "one hundred and four",
        "one hundred and five",
        "one hundred and six",
        "one hundred and seven",
        "one hundred and eight",
        "one hundred and nine",
        "one hundred and ten",
        "one hundred and eleven",
        "one hundred and twelve",
        "one hundred and thirteen",
        "one hundred and fourteen",
        "one hundred and fifteen",
        "one hundred and sixteen",
        "one hundred and seventeen",
        "one hundred and eightteen",
        "one hundred and nineteen",
        "one hundred and twenty",
        "one hundred and twenty one",
        "one hundred and twenty two",
        "one hundred and twenty three",
        "one hundred and twenty four",
        "one hundred and twenty five",
        "one hundred and twenty six",
        "one hundred and twenty seven",
        "one hundred and twenty eight",
        "one hundred and twenty nine",
        "one hundred and thirty",
        "one hundred and thirty one",
        "one hundred and thirty two",
        "one hundred and thirty three",
        "one hundred and thirty four",
        "one hundred and thirty five",
        "one hundred and thirty six",
        "one hundred and thirty seven",
        "one hundred and thirty eight",
        "one hundred and thirty nine",
        "one hundred and forty",
        "one hundred and forty one",
        "one hundred and forty two",
        "one hundred and forty three",
        "one hundred and forty four",
        "one hundred and forty five",
        "one hundred and forty six",
        "one hundred and forty seven",
        "one hundred and forty eight",
        "one hundred and forty nine",
        "one hundred and fifty",
        "one hundred and fifty one",
        "one hundred and fifty two",
        "one hundred and fifty three",
        "one hundred and fifty four",
        "one hundred and fifty five",
        "one hundred and fifty six",
        "one hundred and fifty seven",
        "one hundred and fifty eight",
        "one hundred and fifty nine",
        "one hundred and sixty",
        "one hundred and sixty one",
        "one hundred and sixty two",
        "one hundred and sixty three",
        "one hundred and sixty four",
        "one hundred and sixty five",
        "one hundred and sixty six",
        "one hundred and sixty seven",
        "one hundred and sixty eight",
        "one hundred and sixty nine",
        "one hundred and seventy",
        "one hundred and seventy one",
        "one hundred and seventy two",
        "one hundred and seventy three",
        "one hundred and seventy four",
        "one hundred and seventy five",
        "one hundred and seventy six",
        "one hundred and seventy seven",
        "one hundred and seventy eight",
        "one hundred and seventy nine",
        "one hundred and eighty",
        "one hundred and eighty one",
        "one hundred and eighty two",
        "one hundred and eighty three",
        "one hundred and eighty four",
        "one hundred and eighty five",
        "one hundred and eighty six",
        "one hundred and eighty seven",
        "one hundred and eighty eight",
        "one hundred and eighty nine",
        "one hundred and ninety",
        "one hundred and ninety one",
        "one hundred and ninety two",
        "one hundred and ninety three",
        "one hundred and ninety four",
        "one hundred and ninety five",
        "one hundred and ninety six",
        "one hundred and ninety seven",
        "one hundred and ninety eight",
        "one hundred and ninety nine",
        "two hundred",
    };

    public static String toCardinal(int i)
    {
        if ((i < 1) || (i > CARDINAL.length))
            return String.valueOf(i);
        else
            return CARDINAL[i-1];
    }

    public static String toOrdinal(int i)
    {
        if ((i < 1) || (i > ORDINAL.length))
            return String.valueOf(i);
        else
            return ORDINAL[i-1];
    }
    
    public static Integer getOrdinal(String txt)
    {
        for (int i = 0; i < ORDINAL.length; i++)
            if (ORDINAL[i].equalsIgnoreCase(txt))
                return i + 1;
        return null;
    }
    
    public static Integer getCardinal(String txt)
    {
        for (int i = 0; i < CARDINAL.length; i++)
            if (CARDINAL[i].equalsIgnoreCase(txt))
                return i + 1;
        return null;
    }
    
    public static Integer getEnumeration(String txt)
    {
        Integer ret = null;
        try
        {
            ret = Integer.parseInt(txt);
        }
        catch (NumberFormatException e)
        {                
        }
        if (ret == null)
            ret = getOrdinal(txt);
        if (ret == null)
            ret = getCardinal(txt);
        return ret;
    }
}